In [4]:
n=input()
num=list()
o=list()
op=['+','-','*','/']
i=0
while i<len(n):
    if n[i] in op:
        num.append(n[0:i])
        o.append(n[i])
        n=n[i+1:len(n)]
    i+=1
print(num)
print(o)

6+5+7+3+5+7
['6', '5+7']
['+', '+']


In [36]:
class calc():
    def __init__(a):
        c=input('Enter the exp')
        out=0
        for i in c:
            if i=='+':
                d=c.split(i)
                out=(int(d[0])+int(d[1]))
            print(out)
a=calc()

Enter the exp7+6+5
0
13
13
13
13


In [1]:
a=7+8-2*1
print(a)

13


In [10]:
def add(a):
    res=int(a[0])+int(a[1])
    print(res)
def sub(a):
    res=int(a[0])-int(a[1])
    print(res)
def mul(a):
    res=int(a[0])*int(a[1])
    print(res)
def div(a):
    res=int(a[0])/int(a[1])
    print(res)
def floor(a):
    res=int(a[0])//int(a[1])
    print(res)

n=input()
if '+' in n:
    a=n.split('+')
    add(a)
if '-' in n:
    a=n.split('-')
    sub(a)
if '*' in n:
    a=n.split('*')
    mul(a)
if '/' in n and n.count('/')==1:
    a=n.split('/')
    div(a)  
if '/' in n and n.count('/')==2:
    a=n.split('//')
    floor(a)  

8-8
0


In [115]:
import numpy as np
arr=np.array([1,2,4,6,3,0,5,7,5])
print(arr)
print(type(array))
array.shape
array=arr.reshape(3,3)
print(array)

[1 2 4 6 3 0 5 7 5]
<class 'numpy.ndarray'>
[[1 2 4]
 [6 3 0]
 [5 7 5]]


In [23]:
import numpy as np
a=np.random.randint(0,10000,20)
print(a)

[8812 5283 2094 7239 4042 8076 4089 4228 1165 5917 6289 1184 8718 4463
 5294 3228 8765 4965 7932 8975]


In [29]:
import numpy as np
a=np.arange(1,20)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [53]:
import numpy as np
a=np.random.randint(0,10000,20)
print(a)
res=np.std(a)
print(res)

[4630 1128 4488 9293 8892 1225 3371 6555 4915 9126 3484 2278 4229 1541
 4002 4774 2178 8259 5825 8199]
2626.840143594581


In [66]:
import numpy as np
a=np.random.randint(0,100,20)
print(a)
mean=np.mean(a)
var=0
for i in range(0,len(a)):
    var=var+(a[i]-mean)*(a[i]-mean)
var=var/20
res=np.sqrt(var)
print(res)
res1=np.std(a)
print(res1)


[71 80 58 18 57 72 20 80 95 45 64 41 81 70 94  8 10 50 66  7]
27.817755121504682
27.817755121504682


In [93]:
import numpy as np
a=np.array([1,2,3,4,5])+2
print(a)

[3 4 5 6 7]


In [111]:
import numpy as np
a=np.random.randint(0,100,20)
a=a.reshape(4,5)
print(a)

[[64 55 89 75 65]
 [81  8 12 42 86]
 [83 41 69 55 10]
 [48 50 83 91 34]]


In [113]:
import numpy as np
a=np.array(np.arange(1,21)).reshape(4,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [117]:
import numpy as np
a=np.random.randint(0,100,10)
print(a)
a=a.reshape(2,5)
print(a)

[61 74 31 12 77 78 25 98 88  8]
[[61 74 31 12 77]
 [78 25 98 88  8]]


In [2]:
import pandas as pd
var=pd.Series([1,2,3,4,5])
print(var)
print(type(var))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>


In [8]:
import pandas as pd
var=pd.Series([1,2,3,4,5],index=list('abcde'))
print(var)
print(type(var))

a    1
b    2
c    3
d    4
e    5
dtype: int64
<class 'pandas.core.series.Series'>


In [27]:
import pandas as pd
var=pd.DataFrame([9,2,6,4,5],index=list('abcde'),columns=list('a'))
print(var)
print(type(var))

   a
a  9
b  2
c  6
d  4
e  5
<class 'pandas.core.frame.DataFrame'>


In [35]:
import pandas as pd
var=pd.DataFrame(np.arange(1,21).reshape(4,5),index=list('asdf'),columns=list('qwert'))
print(var)
print(type(var))

    q   w   e   r   t
a   1   2   3   4   5
s   6   7   8   9  10
d  11  12  13  14  15
f  16  17  18  19  20
<class 'pandas.core.frame.DataFrame'>


In [44]:
import pandas as pd
var=pd.DataFrame(np.arange(1,21).reshape(4,5),index=list('asdf'),columns=list('qwert'))
print((var[var>5]).dropna())

      q     w     e     r     t
s   6.0   7.0   8.0   9.0  10.0
d  11.0  12.0  13.0  14.0  15.0
f  16.0  17.0  18.0  19.0  20.0
