In [14]:
import pandas as pd
import numpy as np
var=pd.DataFrame(np.arange(1,21).reshape(4,5),index=list('asdf'),columns=list('qwert'))
print(var)
var['q']

    q   w   e   r   t
a   1   2   3   4   5
s   6   7   8   9  10
d  11  12  13  14  15
f  16  17  18  19  20


a     1
s     6
d    11
f    16
Name: q, dtype: int32

In [6]:
import numpy as np
a=23
b=28
c=7
d=19
e=2
l=[a,b,c,d,e]
sum=0
avg=0
val=0
val1=0
nu=0
de=0
for i in range(0,len(l)):
    sum+=l[i]
    avg=sum/int(len(l))
for i in range(0,len(l)):
    for i in range(0,len(l)):
        val=val+(l[i]-avg)
        nu=val**2
        val1=((l[i]-avg))**2
        val1=val1**2
        de=np.sqrt(val1)
        res=nu/de
        print(res)

1.0
2.528621338349906
1.4509297520661149
18.59765625
6.627690865120872e-32
0.999999999999999
2.5286213383499048
1.450929752066114
18.597656249999993
2.6510763460483487e-31
0.9999999999999981
2.5286213383499043
1.4509297520661129
18.597656249999982
5.964921778608784e-31
0.999999999999997
2.5286213383499034
1.450929752066112
18.59765624999997
1.0604305384193395e-30
0.999999999999996
2.528621338349902
1.450929752066111
18.597656249999964
1.6569227162802177e-30


In [1]:
import numpy as np
def cor(x,y):
    n=x.size
    n1=n*(x*y).sum()
    nr=x.sum()*y.sum()
    num=n1-nr
    d1=n*(x**2).sum()-x.sum()**2
    d2=n*(y**2).sum()-y.sum()**2
    den=(d1*d2)**0.5
    return num/den
a=np.array([1,35,3,4,5])
b=np.array([6,7,8,9,10])
c=np.array([11,28,23,45,12])
d=np.array([23,34,15,18,21])
e=np.array([30,46,51,2,34])
cor(a,b)
def cmatrix(x):
    cm=[]
    ncol=x.shape[1]
    for i in range(ncol):
        m=[]
        for j in range(ncol):
            m.append(cor(x[:,i],x[:,j]))
        cm.append(m)
    return np.array(cm)
M=np.c_[a,b,c,d,e]
print(M)
cmatrix(M)

[[ 1  6 11 23 30]
 [35  7 28 34 46]
 [ 3  8 23 15 51]
 [ 4  9 45 18  2]
 [ 5 10 12 21 34]]


array([[ 1.        , -0.25473918,  0.19881689,  0.89110628,  0.37192553],
       [-0.25473918,  1.        ,  0.2164127 , -0.43560684, -0.29761215],
       [ 0.19881689,  0.2164127 ,  1.        , -0.0739282 , -0.55593453],
       [ 0.89110628, -0.43560684, -0.0739282 ,  1.        ,  0.2708075 ],
       [ 0.37192553, -0.29761215, -0.55593453,  0.2708075 ,  1.        ]])